export type { EmblaOptionsType } from './Options.ts'
export type { EmblaEventType } from './EventHandler.ts'
export type { EmblaPluginType } from './Plugins.ts'
export type { EmblaCarouselType } from './EmblaCarousel.ts'
export { EmblaCarousel } from './EmblaCarousel.ts'
