export type { EmblaOptionsType } from './Options.ts'
export type { EmblaEventType } from './useEventHandler.ts'
export type { EmblaPluginType } from './Plugins.ts'
export type { EmblaCarouselType } from './useEmblaCarousel.ts'
export { useEmblaCarousel } from './useEmblaCarousel.ts'
